// import banner from "./img-resource/banner-produk1.jpg";

const imgBanner = [
  "/src/component/Beranda/img-resource/banner-produk1.jpg",
  "/src/component/Beranda/img-resource/banner-produk2.jpg",
  "/src/component/Beranda/img-resource/banner-produk3.jpg",
  "/src/component/Beranda/img-resource/banner-produk4.jpg",
  "/src/component/Beranda/img-resource/banner-produk5.jpg",
  "/src/component/Beranda/img-resource/banner-produk6.jpg",
  "/src/component/Beranda/img-resource/banner-produk7.jpg",
  "/src/component/Beranda/img-resource/banner-produk8.jpg",
  "/src/component/Beranda/img-resource/banner-produk9.jpg",
];

const imgCustomer = [
  "/src/component/Beranda/img-resource/customer1.png",
  "/src/component/Beranda/img-resource/customer2.png",
  "/src/component/Beranda/img-resource/customer3.png",
  "/src/component/Beranda/img-resource/customer4.png",
  "/src/component/Beranda/img-resource/customer5.png",
  "/src/component/Beranda/img-resource/customer6.png",
  "/src/component/Beranda/img-resource/customer7.png",
  "/src/component/Beranda/img-resource/customer8.png",
  "/src/component/Beranda/img-resource/customer9.png",
];

export const videos = [
  {
    id: 1,
    banner: imgBanner[0],
    title: "Big 4 Auditor Financial Analyst",
    describe:
      "Mulai transformasi dengan instruktur profesional, harga yang terjangkau, dan  kurikulum terbaik",
    img: imgCustomer[0],
    instructor: "Jenna Ortega",
    role: "Senior Accountant at Gojek",
    category: "Bisnis",
    price: "Rp 300K",
    rating: 3.5,
  },
  {
    id: 2,
    banner: imgBanner[1],
    title: "Big 4 Auditor Financial Analyst",
    img: imgCustomer[1],
    instructor: "Jenna Ortega",
    role: "Senior Accountant at Gojek",
    category: "Bisnis",
    price: "Rp 350K",
    rating: 4.0,
  },
  {
    id: 3,
    banner: imgBanner[2],
    title: "Big 4 Auditor Financial Analyst",
    img: imgCustomer[2],
    instructor: "Jenna Ortega",
    role: "Senior Accountant at Gojek",
    category: "Pemasaran",
    price: "Rp 250K",
    rating: 4.2,
  },
  {
    id: 4,
    banner: imgBanner[3],
    title: "Big 4 Auditor Financial Analyst",
    img: imgCustomer[3],
    instructor: "Jenna Ortega",
    role: "Senior Accountant at Gojek",
    category: "Pemasaran",
    price: "Rp 270K",
    rating: 4.1,
  },
  {
    id: 5,
    banner: imgBanner[4],
    title: "Big 4 Auditor Financial Analyst",
    img: imgCustomer[4],
    instructor: "Jenna Ortega",
    role: "Senior Accountant at Gojek",
    category: "Desain",
    price: "Rp 280K",
    rating: 4.5,
  },
  {
    id: 6,
    banner: imgBanner[5],
    title: "Big 4 Auditor Financial Analyst",
    img: imgCustomer[5],
    instructor: "Jenna Ortega",
    role: "Senior Accountant at Gojek",
    category: "Desain",
    price: "Rp 240K",
    rating: 4.3,
  },
  {
    id: 7,
    banner: imgBanner[6],
    title: "Big 4 Auditor Financial Analyst",
    img: imgCustomer[6],
    instructor: "Jenna Ortega",
    role: "Senior Accountant at Gojek",
    category: "Pengembangan Diri",
    price: "Rp 200K",
    rating: 4.6,
  },
  {
    id: 8,
    banner: imgBanner[7],
    title: "Big 4 Auditor Financial Analyst",
    img: imgCustomer[7],
    instructor: "Jenna Ortega",
    role: "Senior Accountant at Gojek",
    category: "Pengembangan Diri",
    price: "Rp 220K",
    rating: 4.7,
  },
  {
    id: 9,
    banner: imgBanner[8],
    title: "Big 4 Auditor Financial Analyst",
    img: imgCustomer[8],
    instructor: "Jenna Ortega",
    role: "Senior Accountant at Gojek",
    category: "Pengembangan Diri",
    price: "Rp 220K",
    rating: 4.7,
  },
];
